### ISSUE TITLE
Possible new organizations

### ISSUE THREAD

**Issue by jpmckinney** [sbaack/github-scraper#1]
[This file](https://github.com/sbaack/github-scraper/blob/master/organizations.txt) is empty, so I don't know where you are storing the list of organizations.

Anyway, here is another list:
https://raw.githubusercontent.com/github/government.github.com/d1bb5f99acd18ffd70d570d5dcecbb349ed867bb/_data/civic_hackers.yml

To which you can add the following:
- azavea
- ciudadanointeligente
- congresointeractivo
- kohovolit
- openkratio
- openpolis
- poplus
- regardscitoyens
- sinar
- cargografias
- cytoscape
- dallasmorningnews
- gephi
- granoproject
- hhba
- iilab
- influencemapping
- jplusplus
- linkurious
- littlesis-org
- medialab
- openc
- openinstitute
- poderomedia
- poderopedia
- pudo
- skomputer
- structr
- texas
- transparencytoolkit
- datamade
- dataprotocols
- govtrack
- opencivicdata
- opendata
- propublica

**Comment by sbaack** [comment]
I left the file in this repo empty in case somebody likes to use this scraper for other purposes. I put the list of organizations in the blog article but I just noticed that the link was broken. [Fixed it now](http://sbaack.com/downloads/data_github_scrape_civic-tech_2015-11-19/organizations.txt). You can also find the list in the repo for my blog now: https://github.com/sbaack/sbaack.github.io/tree/master/downloads/data_github_scrape_civic-tech_2015-11-19

Thanks for your list too! As I'm interested in the connection between civic hackers and journalists, I think it's very interesting that you included journalistic organizations like dallasmorningnews, jplusplus or propublica, those didn't appear in other lists of civic tech organizations I saw so far. I think I should write another blog post about how I compiled the list as it's pretty much open for debate how well it represents the global civic tech community.
